-- 10
SELECT LAST_NAME,HIRE_DATE,TO_CHAR(HIRE_DATE,'DAY') DAY
FROM EMPLOYEES
ORDER BY TRANSLATE(TO_CHAR(HIRE_DATE,'D'),1234567,7123456);

-- 12
SELECT SUBSTR(LAST_NAME,1,8)||REPLACE(LPAD(' ',TRUNC(SALARY/1000),'*'),' ','*') EMPLOYEES_AND_THEIR_SALARIES
FROM EMPLOYEES
ORDER BY SALARY DESC;